// Code generated by mockery v2.42.1. DO NOT EDIT.

package registry

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// mockClientWatcher is an autogenerated mock type for the clientWatcher type
type mockClientWatcher struct {
	mock.Mock
}

type mockClientWatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockClientWatcher) EXPECT() *mockClientWatcher_Expecter {
	return &mockClientWatcher_Expecter{mock: &_m.Mock}
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *mockClientWatcher) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockClientWatcher_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type mockClientWatcher_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *mockClientWatcher_Expecter) Watch(ctx interface{}, opts interface{}) *mockClientWatcher_Watch_Call {
	return &mockClientWatcher_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *mockClientWatcher_Watch_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *mockClientWatcher_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *mockClientWatcher_Watch_Call) Return(_a0 watch.Interface, _a1 error) *mockClientWatcher_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockClientWatcher_Watch_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (watch.Interface, error)) *mockClientWatcher_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// newMockClientWatcher creates a new instance of mockClientWatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockClientWatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockClientWatcher {
	mock := &mockClientWatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
