// Code generated by mockery v2.42.1. DO NOT EDIT.

package registry

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockConfigurationReader is an autogenerated mock type for the ConfigurationReader type
type MockConfigurationReader struct {
	mock.Mock
}

type MockConfigurationReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigurationReader) EXPECT() *MockConfigurationReader_Expecter {
	return &MockConfigurationReader_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function with given fields: ctx, key
func (_m *MockConfigurationReader) Exists(ctx context.Context, key string) (bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigurationReader_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockConfigurationReader_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockConfigurationReader_Expecter) Exists(ctx interface{}, key interface{}) *MockConfigurationReader_Exists_Call {
	return &MockConfigurationReader_Exists_Call{Call: _e.mock.On("Exists", ctx, key)}
}

func (_c *MockConfigurationReader_Exists_Call) Run(run func(ctx context.Context, key string)) *MockConfigurationReader_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConfigurationReader_Exists_Call) Return(_a0 bool, _a1 error) *MockConfigurationReader_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigurationReader_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockConfigurationReader_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockConfigurationReader) Get(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigurationReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockConfigurationReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockConfigurationReader_Expecter) Get(ctx interface{}, key interface{}) *MockConfigurationReader_Get_Call {
	return &MockConfigurationReader_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockConfigurationReader_Get_Call) Run(run func(ctx context.Context, key string)) *MockConfigurationReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConfigurationReader_Get_Call) Return(_a0 string, _a1 error) *MockConfigurationReader_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigurationReader_Get_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockConfigurationReader_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockConfigurationReader) GetAll(ctx context.Context) (map[string]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigurationReader_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockConfigurationReader_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigurationReader_Expecter) GetAll(ctx interface{}) *MockConfigurationReader_GetAll_Call {
	return &MockConfigurationReader_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockConfigurationReader_GetAll_Call) Run(run func(ctx context.Context)) *MockConfigurationReader_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConfigurationReader_GetAll_Call) Return(_a0 map[string]string, _a1 error) *MockConfigurationReader_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigurationReader_GetAll_Call) RunAndReturn(run func(context.Context) (map[string]string, error)) *MockConfigurationReader_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigurationReader creates a new instance of MockConfigurationReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigurationReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigurationReader {
	mock := &MockConfigurationReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
