// Code generated by mockery v2.42.1. DO NOT EDIT.

package repository

import mock "github.com/stretchr/testify/mock"

// mockResourceVersionGetter is an autogenerated mock type for the resourceVersionGetter type
type mockResourceVersionGetter struct {
	mock.Mock
}

type mockResourceVersionGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockResourceVersionGetter) EXPECT() *mockResourceVersionGetter_Expecter {
	return &mockResourceVersionGetter_Expecter{mock: &_m.Mock}
}

// GetResourceVersion provides a mock function with given fields:
func (_m *mockResourceVersionGetter) GetResourceVersion() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResourceVersion")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// mockResourceVersionGetter_GetResourceVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceVersion'
type mockResourceVersionGetter_GetResourceVersion_Call struct {
	*mock.Call
}

// GetResourceVersion is a helper method to define mock.On call
func (_e *mockResourceVersionGetter_Expecter) GetResourceVersion() *mockResourceVersionGetter_GetResourceVersion_Call {
	return &mockResourceVersionGetter_GetResourceVersion_Call{Call: _e.mock.On("GetResourceVersion")}
}

func (_c *mockResourceVersionGetter_GetResourceVersion_Call) Run(run func()) *mockResourceVersionGetter_GetResourceVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockResourceVersionGetter_GetResourceVersion_Call) Return(_a0 string) *mockResourceVersionGetter_GetResourceVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockResourceVersionGetter_GetResourceVersion_Call) RunAndReturn(run func() string) *mockResourceVersionGetter_GetResourceVersion_Call {
	_c.Call.Return(run)
	return _c
}

// newMockResourceVersionGetter creates a new instance of mockResourceVersionGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockResourceVersionGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockResourceVersionGetter {
	mock := &mockResourceVersionGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
