// Code generated by mockery v2.52.3. DO NOT EDIT.

package repository

import (
	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// mockResourceMetaAccessor is an autogenerated mock type for the resourceMetaAccessor type
type mockResourceMetaAccessor struct {
	mock.Mock
}

type mockResourceMetaAccessor_Expecter struct {
	mock *mock.Mock
}

func (_m *mockResourceMetaAccessor) EXPECT() *mockResourceMetaAccessor_Expecter {
	return &mockResourceMetaAccessor_Expecter{mock: &_m.Mock}
}

// GetCreationTimestamp provides a mock function with no fields
func (_m *mockResourceMetaAccessor) GetCreationTimestamp() v1.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCreationTimestamp")
	}

	var r0 v1.Time
	if rf, ok := ret.Get(0).(func() v1.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(v1.Time)
	}

	return r0
}

// mockResourceMetaAccessor_GetCreationTimestamp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreationTimestamp'
type mockResourceMetaAccessor_GetCreationTimestamp_Call struct {
	*mock.Call
}

// GetCreationTimestamp is a helper method to define mock.On call
func (_e *mockResourceMetaAccessor_Expecter) GetCreationTimestamp() *mockResourceMetaAccessor_GetCreationTimestamp_Call {
	return &mockResourceMetaAccessor_GetCreationTimestamp_Call{Call: _e.mock.On("GetCreationTimestamp")}
}

func (_c *mockResourceMetaAccessor_GetCreationTimestamp_Call) Run(run func()) *mockResourceMetaAccessor_GetCreationTimestamp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockResourceMetaAccessor_GetCreationTimestamp_Call) Return(_a0 v1.Time) *mockResourceMetaAccessor_GetCreationTimestamp_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockResourceMetaAccessor_GetCreationTimestamp_Call) RunAndReturn(run func() v1.Time) *mockResourceMetaAccessor_GetCreationTimestamp_Call {
	_c.Call.Return(run)
	return _c
}

// GetManagedFields provides a mock function with no fields
func (_m *mockResourceMetaAccessor) GetManagedFields() []v1.ManagedFieldsEntry {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetManagedFields")
	}

	var r0 []v1.ManagedFieldsEntry
	if rf, ok := ret.Get(0).(func() []v1.ManagedFieldsEntry); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.ManagedFieldsEntry)
		}
	}

	return r0
}

// mockResourceMetaAccessor_GetManagedFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManagedFields'
type mockResourceMetaAccessor_GetManagedFields_Call struct {
	*mock.Call
}

// GetManagedFields is a helper method to define mock.On call
func (_e *mockResourceMetaAccessor_Expecter) GetManagedFields() *mockResourceMetaAccessor_GetManagedFields_Call {
	return &mockResourceMetaAccessor_GetManagedFields_Call{Call: _e.mock.On("GetManagedFields")}
}

func (_c *mockResourceMetaAccessor_GetManagedFields_Call) Run(run func()) *mockResourceMetaAccessor_GetManagedFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockResourceMetaAccessor_GetManagedFields_Call) Return(_a0 []v1.ManagedFieldsEntry) *mockResourceMetaAccessor_GetManagedFields_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockResourceMetaAccessor_GetManagedFields_Call) RunAndReturn(run func() []v1.ManagedFieldsEntry) *mockResourceMetaAccessor_GetManagedFields_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceVersion provides a mock function with no fields
func (_m *mockResourceMetaAccessor) GetResourceVersion() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResourceVersion")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// mockResourceMetaAccessor_GetResourceVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceVersion'
type mockResourceMetaAccessor_GetResourceVersion_Call struct {
	*mock.Call
}

// GetResourceVersion is a helper method to define mock.On call
func (_e *mockResourceMetaAccessor_Expecter) GetResourceVersion() *mockResourceMetaAccessor_GetResourceVersion_Call {
	return &mockResourceMetaAccessor_GetResourceVersion_Call{Call: _e.mock.On("GetResourceVersion")}
}

func (_c *mockResourceMetaAccessor_GetResourceVersion_Call) Run(run func()) *mockResourceMetaAccessor_GetResourceVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockResourceMetaAccessor_GetResourceVersion_Call) Return(_a0 string) *mockResourceMetaAccessor_GetResourceVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockResourceMetaAccessor_GetResourceVersion_Call) RunAndReturn(run func() string) *mockResourceMetaAccessor_GetResourceVersion_Call {
	_c.Call.Return(run)
	return _c
}

// newMockResourceMetaAccessor creates a new instance of mockResourceMetaAccessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockResourceMetaAccessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockResourceMetaAccessor {
	mock := &mockResourceMetaAccessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
