// Code generated by mockery v2.42.1. DO NOT EDIT.

package repository

import (
	io "io"

	config "github.com/cloudogu/k8s-registry-lib/config"

	mock "github.com/stretchr/testify/mock"
)

// mockConverter is an autogenerated mock type for the converter type
type mockConverter struct {
	mock.Mock
}

type mockConverter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConverter) EXPECT() *mockConverter_Expecter {
	return &mockConverter_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with given fields: reader
func (_m *mockConverter) Read(reader io.Reader) (config.Entries, error) {
	ret := _m.Called(reader)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 config.Entries
	var r1 error
	if rf, ok := ret.Get(0).(func(io.Reader) (config.Entries, error)); ok {
		return rf(reader)
	}
	if rf, ok := ret.Get(0).(func(io.Reader) config.Entries); ok {
		r0 = rf(reader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Entries)
		}
	}

	if rf, ok := ret.Get(1).(func(io.Reader) error); ok {
		r1 = rf(reader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockConverter_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type mockConverter_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - reader io.Reader
func (_e *mockConverter_Expecter) Read(reader interface{}) *mockConverter_Read_Call {
	return &mockConverter_Read_Call{Call: _e.mock.On("Read", reader)}
}

func (_c *mockConverter_Read_Call) Run(run func(reader io.Reader)) *mockConverter_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader))
	})
	return _c
}

func (_c *mockConverter_Read_Call) Return(_a0 config.Entries, _a1 error) *mockConverter_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockConverter_Read_Call) RunAndReturn(run func(io.Reader) (config.Entries, error)) *mockConverter_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: writer, cfgData
func (_m *mockConverter) Write(writer io.Writer, cfgData config.Entries) error {
	ret := _m.Called(writer, cfgData)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Writer, config.Entries) error); ok {
		r0 = rf(writer, cfgData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockConverter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type mockConverter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - writer io.Writer
//   - cfgData config.Entries
func (_e *mockConverter_Expecter) Write(writer interface{}, cfgData interface{}) *mockConverter_Write_Call {
	return &mockConverter_Write_Call{Call: _e.mock.On("Write", writer, cfgData)}
}

func (_c *mockConverter_Write_Call) Run(run func(writer io.Writer, cfgData config.Entries)) *mockConverter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer), args[1].(config.Entries))
	})
	return _c
}

func (_c *mockConverter_Write_Call) Return(_a0 error) *mockConverter_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockConverter_Write_Call) RunAndReturn(run func(io.Writer, config.Entries) error) *mockConverter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// newMockConverter creates a new instance of mockConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConverter {
	mock := &mockConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
