// Code generated by mockery v2.42.1. DO NOT EDIT.

package dogu

import (
	mock "github.com/stretchr/testify/mock"
	cache "k8s.io/client-go/tools/cache"

	v1 "k8s.io/client-go/listers/core/v1"
)

// mockConfigMapInformer is an autogenerated mock type for the configMapInformer type
type mockConfigMapInformer struct {
	mock.Mock
}

type mockConfigMapInformer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConfigMapInformer) EXPECT() *mockConfigMapInformer_Expecter {
	return &mockConfigMapInformer_Expecter{mock: &_m.Mock}
}

// Informer provides a mock function with given fields:
func (_m *mockConfigMapInformer) Informer() cache.SharedIndexInformer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Informer")
	}

	var r0 cache.SharedIndexInformer
	if rf, ok := ret.Get(0).(func() cache.SharedIndexInformer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cache.SharedIndexInformer)
		}
	}

	return r0
}

// mockConfigMapInformer_Informer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Informer'
type mockConfigMapInformer_Informer_Call struct {
	*mock.Call
}

// Informer is a helper method to define mock.On call
func (_e *mockConfigMapInformer_Expecter) Informer() *mockConfigMapInformer_Informer_Call {
	return &mockConfigMapInformer_Informer_Call{Call: _e.mock.On("Informer")}
}

func (_c *mockConfigMapInformer_Informer_Call) Run(run func()) *mockConfigMapInformer_Informer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConfigMapInformer_Informer_Call) Return(_a0 cache.SharedIndexInformer) *mockConfigMapInformer_Informer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockConfigMapInformer_Informer_Call) RunAndReturn(run func() cache.SharedIndexInformer) *mockConfigMapInformer_Informer_Call {
	_c.Call.Return(run)
	return _c
}

// Lister provides a mock function with given fields:
func (_m *mockConfigMapInformer) Lister() v1.ConfigMapLister {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Lister")
	}

	var r0 v1.ConfigMapLister
	if rf, ok := ret.Get(0).(func() v1.ConfigMapLister); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ConfigMapLister)
		}
	}

	return r0
}

// mockConfigMapInformer_Lister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lister'
type mockConfigMapInformer_Lister_Call struct {
	*mock.Call
}

// Lister is a helper method to define mock.On call
func (_e *mockConfigMapInformer_Expecter) Lister() *mockConfigMapInformer_Lister_Call {
	return &mockConfigMapInformer_Lister_Call{Call: _e.mock.On("Lister")}
}

func (_c *mockConfigMapInformer_Lister_Call) Run(run func()) *mockConfigMapInformer_Lister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConfigMapInformer_Lister_Call) Return(_a0 v1.ConfigMapLister) *mockConfigMapInformer_Lister_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockConfigMapInformer_Lister_Call) RunAndReturn(run func() v1.ConfigMapLister) *mockConfigMapInformer_Lister_Call {
	_c.Call.Return(run)
	return _c
}

// newMockConfigMapInformer creates a new instance of mockConfigMapInformer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConfigMapInformer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConfigMapInformer {
	mock := &mockConfigMapInformer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
